// @ts-check
import { defineConfig } from 'astro/config';

const redirectTarget = 'https://www.mindstatelabs.com/';

// https://astro.build/config
export default defineConfig({
	base: '/',
	output: 'static',
	site: 'https://binauralbeatstudio.com',
	trailingSlash: 'always',
	build: {
		format: 'directory',
	},
	devToolbar: {
		enabled: false,
	},
	redirects: {
		'/': redirectTarget,
		'/benefits': redirectTarget,
		'/demo': redirectTarget,
		'/screenshots': redirectTarget,
		'/privacy': redirectTarget,
		'/terms': redirectTarget,
		'/ar': redirectTarget,
		'/ar/benefits': redirectTarget,
		'/ar/demo': redirectTarget,
		'/ar/screenshots': redirectTarget,
		'/es': redirectTarget,
		'/es/benefits': redirectTarget,
		'/es/demo': redirectTarget,
		'/es/screenshots': redirectTarget,
		'/hi': redirectTarget,
		'/hi/benefits': redirectTarget,
		'/hi/demo': redirectTarget,
		'/hi/screenshots': redirectTarget,
		'/id': redirectTarget,
		'/id/benefits': redirectTarget,
		'/id/demo': redirectTarget,
		'/id/screenshots': redirectTarget,
		'/ja': redirectTarget,
		'/ja/benefits': redirectTarget,
		'/ja/demo': redirectTarget,
		'/ja/screenshots': redirectTarget,
		'/nl': redirectTarget,
		'/nl/benefits': redirectTarget,
		'/nl/demo': redirectTarget,
		'/nl/screenshots': redirectTarget,
		'/pt': redirectTarget,
		'/pt/benefits': redirectTarget,
		'/pt/demo': redirectTarget,
		'/pt/screenshots': redirectTarget,
		'/ru': redirectTarget,
		'/ru/benefits': redirectTarget,
		'/ru/demo': redirectTarget,
		'/ru/screenshots': redirectTarget,
		'/zh': redirectTarget,
		'/zh/benefits': redirectTarget,
		'/zh/demo': redirectTarget,
		'/zh/screenshots': redirectTarget,
	},
});
